// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    // Dzięki temu `prisma migrate reset` od razu odtwarza dane demo.
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // Migracje idą DIRECT_URL, jeśli jest ustawiony.
    //
    // Na serverless aplikacja łączy się przez transaction pooler (Supabase,
    // port 6543), który nie obsługuje instrukcji wymaganych przez migracje —
    // `prisma migrate deploy` po nim po prostu pada. Do migracji potrzebne
    // jest połączenie sesyjne (port 5432), i to właśnie trzyma DIRECT_URL.
    // Lokalnie i na hostingu z jednym procesem wystarcza sam DATABASE_URL.
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
